### ISSUE TITLE
Switch to dynamic linked library approach to avoid L-GPL copy left clauses

### ISSUE THREAD

**Issue by MarkusTiede** [baloise-incubator/gitopscli#54]
In my opinion we do not (yet) meet the necessary dynamic [LGPL linking requirements](https://opensource.google/docs/thirdparty/licenses/#LinkingRequirements) to take advantage of the **reduced** requirements.

The [Apache Legal docs](https://www.apache.org/legal/resolved.html#category-x) also state that such a dependency is not possible.

As this is a standalone CLI application the site note for [LGPL Combined Libraries](https://www.gnu.org/licenses/lgpl-3.0.html#section5) is also not applicable.

IMHO **we should either (preferably) switch to a dynamic linking approach** (having an *.so or *.ddl or similar) <or> respect LGPL-3.0 license and change projects license to (L)GPL-3.0 instead of Apache 2.0 and meet their requirements.

**Comment by christiansiegel** [comment]
runtime:
- [GitPython](https://github.com/gitpython-developers/GitPython): [BSD 3-Clause](https://github.com/gitpython-developers/GitPython/blob/master/LICENSE)
- [ruamel.yaml](https://sourceforge.net/projects/ruamel-yaml/): [MIT License](https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree/LICENSE)
- [atlassian-python-api](https://github.com/atlassian-api/atlassian-python-api): [Apache License 2.0](https://github.com/atlassian-api/atlassian-python-api/blob/master/LICENSE)
- [PyGithub](https://github.com/PyGithub/PyGithub): [LGPL-3.0](https://github.com/PyGithub/PyGithub/blob/master/COPYING)

dev:
- [black](https://github.com/psf/black): [MIT License](https://github.com/psf/black/blob/master/LICENSE)
- [pylint](https://github.com/PyCQA/pylint): [GPL 2.0](https://github.com/PyCQA/pylint/blob/master/COPYING)
- [pytest](https://github.com/pytest-dev/pytest/): [MIT License](https://github.com/pytest-dev/pytest/blob/master/LICENSE)

**Comment by christiansiegel** [comment]
IMO all python libraries are "dynamically" linked by design. They are downloaded from the [Python Package Index (PyPI)](https://pypi.org/) during installation (as specified in [requirements.txt](https://github.com/baloise-incubator/gitopscli/blob/master/requirements.txt)).
However I'm not sure about the implications of distributing the CLI in a docker image, as the LGPL library is effectively included. However, the user is still able to see the full source code of the library (as provided by PyPI) and replace the library in the docker image.
